<a href="https://colab.research.google.com/github/Chimatanagagopal/DEEP-LEARNING_practice/blob/main/neural_network_approach_to_iris_dataset_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**An approach of Neural Network to predict Iris Species**

This notebook explains about single layer perceptron and multilayer Neural Network (Deep NN) to predict the species of the Iris dataset.

In [ ]:
# Keras
# tensorflow

In [ ]:
#Import required libraries
import keras #library for neural network
import pandas as pd #loading data in table form
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import numpy as np # linear algebra
from sklearn.preprocessing import normalize # machine learning algorithm library

In [ ]:
#Reading data
data=pd.read_csv("/content/iris.csv")
# print("Describing the data: ",data.describe())
# print("Info of the data:",data.info())
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df = data.sample(n = 5)
df

     sepal_length  sepal_width  petal_length  petal_width species
76            6.8          2.8           4.8          1.4       1
97            6.2          2.9           4.3          1.3       1
99            5.7          2.8           4.1          1.3       1
69            5.6          2.5           3.9          1.1       1
115           6.4          3.2           5.3          2.3       2

In [ ]:
print("10 first samples of the dataset:",data.head(10))
print("10 last samples of the dataset:",data.tail(10))

10 first samples of the dataset:      sepal_length  sepal_width  petal_length  petal_width species
89            5.5          2.5           4.0          1.3       1
81            5.5          2.4           3.7          1.0       1
35            5.0          3.2           1.2          0.2       0
121           5.6          2.8           4.9          2.0       2
95            5.7          3.0           4.2          1.2       1
8             4.4          2.9           1.4          0.2       0
40            5.0          3.5           1.3          0.3       0
28            5.2          3.4           1.4          0.2       0
142           5.8          2.7           5.1          1.9       2
77            6.7          3.0           5.0          1.7       1
10 last samples of the dataset:      sepal_length  sepal_width  petal_length  petal_width species
20            5.4          3.4           1.7          0.2       0
62            6.0          2.2           4.0          1.0       1
68            6.2          2.2           4.5          1.5       1
109           7.2          3.6           6.1          2.5       2
136           6.3          3.4           5.6          2.4       2
11            4.8          3.4           1.6          0.2       0
129           7.2          3.0           5.8          1.6       2
126           6.2          2.8           4.8          1.8       2
17            5.1          3.5           1.4          0.3       0
56            6.3          3.3           4.7          1.6       1

In [ ]:
data["species"].unique()

array([0, 1, 2], dtype=object)

In [ ]:
data.shape

(150, 5)

In [ ]:
data.loc[data["species"]=="setosa","species"]=0
data.loc[data["species"]=="versicolor","species"]=1
data.loc[data["species"]=="virginica","species"]=2
print(data.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [ ]:
data=data.iloc[np.random.permutation(len(data))]
print(data.head()) # shuffling the data

     sepal_length  sepal_width  petal_length  petal_width species
89            5.5          2.5           4.0          1.3       1
81            5.5          2.4           3.7          1.0       1
35            5.0          3.2           1.2          0.2       0
121           5.6          2.8           4.9          2.0       2
95            5.7          3.0           4.2          1.2       1

Converting data to numpy array in order for processing

In [ ]:
X=data.iloc[:,:4].values
y=data.iloc[:,4].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)
print("Examples of X\n",X[:3])
print("Examples of y\n",y[:3])

Shape of X (150, 4)
Shape of y (150,)
Examples of X
 [[5.5 2.5 4.  1.3]
 [5.5 2.4 3.7 1. ]
 [5.  3.2 1.2 0.2]]
Examples of y
 [1 1 0]

In [ ]:
data.shape

(150, 5)

**Normalization**

It can be seen from above that the feature of the first dataset has 6cm in Sepal Length, 3.4cm in Sepal Width, 4.5cm in Petal Length and 1.6cm in Petal Width. However, the range of the dataset may be different. Therefore, in order to maintain a good accuracy, the feature of each dataset must be normalized to a range of 0-1 for processing

In [ ]:
X_normalized = normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[0.07609697 0.06617903 0.07870418 0.07476947]
 [0.07609697 0.06353187 0.07280136 0.05751497]
 [0.06917906 0.08470916 0.02361125 0.01150299]]

In [ ]:
#Creating train,test and validation data
'''
80% -- train data
20% -- test data
'''
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

print("Length of train set x:",X_train.shape[0],"y:",y_train.shape[0])
print("Length of test set x:",X_test.shape[0],"y:",y_test.shape[0])

Length of train set x: 120 y: 120
Length of test set x: 30 y: 30

In [ ]:
#Neural network module
from keras.models import Sequential
from keras.layers import Dense,Activation
# from keras.utils import np_utils
import tensorflow as tf

In [ ]:
y_train

In [ ]:
#Change the label to one hot vector
'''
[0]--->[1 0 0]
[1]--->[0 1 0]
[2]--->[0 0 1]
'''
y_train=tf.keras.utils.to_categorical (y_train,num_classes=3)
y_test=tf.keras.utils.to_categorical (y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

Shape of y_train (120, 3)
Shape of y_test (30, 3)

In [ ]:
# # multi-class classification
# # # define the keras model
model = Sequential()

model.add(Dense(32, input_dim=4, activation="relu"))  # 1st hidden layer
model.add(Dense(64, activation="relu")) # 2nd hidden layer
model.add(Dense(128, activation="relu")) # 3rd hidden layer
model.add(Dense(256, activation="relu"))

model.add(Dense(3, activation='softmax')) # output layer

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(loss='categorical_crossentropy',# error
              optimizer='adam',# gradient descent
              metrics=['accuracy'] # accuracy
              )

In [ ]:
# # Regression
# model = Sequential()
# model.add(Dense(32, input_dim = 4,activation = 'relu'))
# model.add(Dense(64, activation = 'relu'))
# model.add(Dense(128, activation = 'relu'))
# model.add(Dense(256, activation = 'relu'))
# model.add(Dense(1)) # output layer

In [ ]:
# two-class classification
# model = Sequential()
# model.add(Dense(32,input_dim=4,activation = 'relu'))
# model.add(Dense(64, activation = 'relu'))
# model.add(Dense(128, activation = 'relu'))
# model.add(Dense(256, activation = 'relu'))

# model.add(Dense(1,activation='sigmoid'))

In [ ]:
# multi-class classification
# model = Sequential()
# model.add(Dense(32,input_dim=4,activation = 'relu'))
# model.add(Dense(64, activation = 'relu'))
# model.add(Dense(128, activation = 'relu'))
# model.add(Dense(256, activation = 'relu'))

# model.add(Dense(3,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# model.compile(loss='categorical_crossentropy',metrics=['accuracy', "recall"])

In [ ]:
model.fit(X_train,y_train,
          validation_data=(X_test,y_test),
          batch_size=30,
          epochs=30)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 145ms/step - accuracy: 0.3333 - loss: 1.0969 - val_accuracy: 0.3333 - val_loss: 1.0905
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4667 - loss: 1.0876 - val_accuracy: 0.6333 - val_loss: 1.0828
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6750 - loss: 1.0775 - val_accuracy: 0.6333 - val_loss: 1.0701
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6750 - loss: 1.0627 - val_accuracy: 0.6333 - val_loss: 1.0523
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6750 - loss: 1.0420 - val_accuracy: 0.6333 - val_loss: 1.0275
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6750 - loss: 1.0119 - val_accuracy: 0.6333 - val_loss: 0.9920
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6750 - loss: 0.9702 - val_accuracy: 0.6333 - val_loss: 0.9453
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6750 - loss: 0.9171 - val_accuracy: 0.6333 - val_loss: 0.8833
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6750 - loss: 0.8463 - val_accuracy: 0.6333 - val_loss: 0.8092
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6750 - loss: 0.7743 - val_accuracy: 0.6333 - val_loss: 0.7301
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6750 - loss: 0.6899 - val_accuracy: 0.6333 - val_loss: 0.6556
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6750 - loss: 0.6031 - val_accuracy: 0.6333 - val_loss: 0.5793
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7000 - loss: 0.5270 - val_accuracy: 0.6667 - val_loss: 0.5103
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7250 - loss: 0.4608 - val_accuracy: 0.8000 - val_loss: 0.4465
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9083 - loss: 0.4006 - val_accuracy: 0.9333 - val_loss: 0.3919
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9750 - loss: 0.3564 - val_accuracy: 0.9333 - val_loss: 0.3502
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9500 - loss: 0.3153 - val_accuracy: 0.9333 - val_loss: 0.3075
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.2779 - val_accuracy: 1.0000 - val_loss: 0.2650
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9750 - loss: 0.2465 - val_accuracy: 0.9333 - val_loss: 0.2553
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9833 - loss: 0.2132 - val_accuracy: 0.9667 - val_loss: 0.2029
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9667 - loss: 0.1827 - val_accuracy: 0.9333 - val_loss: 0.2046
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9667 - loss: 0.1594 - val_accuracy: 1.0000 - val_loss: 0.1558
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9750 - loss: 0.1420 - val_accuracy: 0.9333 - val_loss: 0.1589
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9667 - loss: 0.1477 - val_accuracy: 0.9667 - val_loss: 0.1295
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9917 - loss: 0.1147 - val_accuracy: 0.9667 - val_loss: 0.1175
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9667 - loss: 0.1045 - val_accuracy: 0.9333 - val_loss: 0.1392
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9667 - loss: 0.0939 - val_accuracy: 0.9667 - val_loss: 0.1035
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9667 - loss: 0.0898 - val_accuracy: 0.9667 - val_loss: 0.1110
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9667 - loss: 0.0820 - val_accuracy: 0.9667 - val_loss: 0.0993
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9750 - loss: 0.0790 - val_accuracy: 0.9667 - val_loss: 0.0976

In [ ]:
prediction=model.predict(X_test)
length=len(prediction)

y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100
print("Accuracy of the dataset",accuracy )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
Accuracy of the dataset 96.66666666666667